<a href="https://colab.research.google.com/github/alkhurayjah/Task_DL/blob/main/Saad_alshahrani_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

✅ 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping

✅ 2. Load Dataset

In [2]:
df = pd.read_csv("creditcard.csv")
print(df.shape)
df.head()

(166510, 31)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [6]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

✅ 3. Data Preprocessing

Handle missing values

In [8]:
df = df.fillna(df.median())
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

Handle imbalance

In [9]:
print(df['Class'].value_counts())

Class
0.0    166152
1.0       358
Name: count, dtype: int64

Split features and target

In [10]:
X = df.drop("Class", axis=1)
y = df["Class"]

Train-test split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

Normalize data

In [12]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

✅ 4. Build ANN Model

In [13]:
model = models.Sequential([

    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],),
                 kernel_regularizer=tf.keras.regularizers.l2(0.001)),
    layers.Dropout(0.3),

    layers.Dense(32, activation='relu',
                 kernel_regularizer=tf.keras.regularizers.l2(0.001)),
    layers.Dropout(0.3),

    layers.Dense(16, activation='relu'),

    layers.Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

✅ 5. Compile Model

In [14]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

✅ 6. Add Early Stopping

In [15]:
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

✅ 7. Train Model

In [16]:
history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=256,
    callbacks=[early_stop]
)

Epoch 1/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.9918 - loss: 0.1128 - val_accuracy: 0.9984 - val_loss: 0.0505
Epoch 2/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9990 - loss: 0.0348 - val_accuracy: 0.9988 - val_loss: 0.0241
Epoch 3/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9992 - loss: 0.0168 - val_accuracy: 0.9989 - val_loss: 0.0137
Epoch 4/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9992 - loss: 0.0095 - val_accuracy: 0.9989 - val_loss: 0.0094
Epoch 5/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9992 - loss: 0.0065 - val_accuracy: 0.9989 - val_loss: 0.0076
Epoch 6/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9992 - loss: 0.0053 - val_accuracy: 0.9988 - val_loss: 0.0068
Epoch 7/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9993 - loss: 0.0048 - val_accuracy: 0.9988 - val_loss: 0.0066
Epoch 8/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9992 - loss: 0.0047 - val_accuracy: 0.9989 - val_loss: 0.0063
Epoch 9/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9992 - loss: 0.0044 - val_accuracy: 0.9988 - val_loss: 0.0062
Epoch 10/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9992 - loss: 0.0046 - val_accuracy: 0.9989 - val_loss: 0.0064
Epoch 11/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9993 - loss: 0.0046 - val_accuracy: 0.9989 - val_loss: 0.0069
Epoch 12/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9992 - loss: 0.0046 - val_accuracy: 0.9988 - val_loss: 0.0062
Epoch 13/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9992 - loss: 0.0045 - val_accuracy: 0.9989 - val_loss: 0.0069
Epoch 14/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9992 - loss: 0.0045 - val_accuracy: 0.9989 - val_loss: 0.0067
Epoch 15/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9992 - loss: 0.0046 - val_accuracy: 0.9989 - val_loss: 0.0067
Epoch 16/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9993 - loss: 0.0044 - val_accuracy: 0.9989 - val_loss: 0.0063
Epoch 17/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9993 - loss: 0.0043 - val_accuracy: 0.9989 - val_loss: 0.0070

✅ 8. Evaluate Model

In [17]:
y_pred = (model.predict(X_test) > 0.5).astype(int)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

1041/1041 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step
[[33213    17]
 [   10    62]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     33230
         1.0       0.78      0.86      0.82        72

    accuracy                           1.00     33302
   macro avg       0.89      0.93      0.91     33302
weighted avg       1.00      1.00      1.00     33302

✅ 9. Save Model

In [18]:
model.save("fraud_detection_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

✅ 10. Load Model

In [19]:
loaded_model = tf.keras.models.load_model("fraud_detection_model.h5")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

✅ 11. Inference Function

In [20]:
def predict_transaction(sample):
    sample = scaler.transform([sample])
    prob = loaded_model.predict(sample)[0][0]

    if prob > 0.5:
        return "Fraud ❌"
    else:
        return "Normal ✅"

improve performance

In [21]:
from sklearn.utils import class_weight
weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

class_weights = dict(enumerate(weights))
print(class_weights)

{0: np.float64(0.5010758189013106), 1: np.float64(232.88111888111888)}

In [22]:
history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=256,
    callbacks=[early_stop],
    class_weight=class_weights
)

Epoch 1/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - accuracy: 0.9431 - loss: 0.2869 - val_accuracy: 0.9702 - val_loss: 0.0848
Epoch 2/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9494 - loss: 0.2060 - val_accuracy: 0.9570 - val_loss: 0.1034
Epoch 3/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9532 - loss: 0.1589 - val_accuracy: 0.9556 - val_loss: 0.1089
Epoch 4/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9610 - loss: 0.1309 - val_accuracy: 0.9483 - val_loss: 0.1457
Epoch 5/50
417/417 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9563 - loss: 0.1375 - val_accuracy: 0.9539 - val_loss: 0.1214